[package]
name = "hedgehog"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.13.1", features = [ "tokio", "async-std"] }
reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1.36.0", features = ["full"] }
log = "0.4"
env_logger = "0.11"
dotenv = "0.15"
